### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by david4096** [dcppc/crosscut-metadata#19]
What is the expected license? Currently can't find it.

**Comment by proccaserra** [comment]
@david4096 the license information is absent from the examples posted on crosscut-metadata but you can find a DATS example carrying license information in datatagsuite repo

https://github.com/datatagsuite/examples/blob/master/datacommons/dats_phs001143.json

We'll synch the 2 repo and the examples.

DATS/crosscut-metadata license schema can be found here:
https://github.com/datatagsuite/schema/blob/master/license_schema.json

we are considering an extension to this object to accommodate markup with ontology terms (e.g Data Use Ontology /ADA-Matrix from GA4GH). See here:
the extension would allow for specific tags in order to fetch "dataUseCondition" and "consentInformation 
https://github.com/datatagsuite/schema/blob/dats-datause/license_schema.json

We'll work with Team Phosphorous to update the exemplar files.

**Comment by jonathancrabtree** [comment]
@proccaserra I think @david4096 may be referring to the license for the repo as a whole (is that right, David?) If so, it's a good question (or should I say a FAIR one?) and I don't immediately know the answer. It's possible that Team Copper or someone else has proposed a standard license for DCPPC-related content, but it's not something I've come across yet so I'll have to follow up and get back to you.
